// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz5LyBjTl3XuOQ6GnNnpgaUWuLP2wAq_g',
    appId: '1:1078096613189:web:5c570ea861f3e97b6b382c',
    messagingSenderId: '1078096613189',
    projectId: 'gogreen-ca782',
    authDomain: 'gogreen-ca782.firebaseapp.com',
    storageBucket: 'gogreen-ca782.appspot.com',
    measurementId: 'G-9SX9YN44HH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB01N1bYHrvbkyRs6e43KEJaVJtILa0J0s',
    appId: '1:1078096613189:android:9e25f4ba3ead7b706b382c',
    messagingSenderId: '1078096613189',
    projectId: 'gogreen-ca782',
    storageBucket: 'gogreen-ca782.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkYs9yWtr4x-z0Ts8K5A5wMFbqq0F2cyg',
    appId: '1:1078096613189:ios:7e163c8d25e361e96b382c',
    messagingSenderId: '1078096613189',
    projectId: 'gogreen-ca782',
    storageBucket: 'gogreen-ca782.appspot.com',
    iosBundleId: 'com.example.gogreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkYs9yWtr4x-z0Ts8K5A5wMFbqq0F2cyg',
    appId: '1:1078096613189:ios:7e163c8d25e361e96b382c',
    messagingSenderId: '1078096613189',
    projectId: 'gogreen-ca782',
    storageBucket: 'gogreen-ca782.appspot.com',
    iosBundleId: 'com.example.gogreen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz5LyBjTl3XuOQ6GnNnpgaUWuLP2wAq_g',
    appId: '1:1078096613189:web:de784349baf6f3e56b382c',
    messagingSenderId: '1078096613189',
    projectId: 'gogreen-ca782',
    authDomain: 'gogreen-ca782.firebaseapp.com',
    storageBucket: 'gogreen-ca782.appspot.com',
    measurementId: 'G-5WWDJJLW33',
  );
}
